# fly.toml app configuration file generated for tennis-scheduler-tfc on 2025-09-03T04:56:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tennis-scheduler-tfc'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "1800s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
